// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCPcZ_udKbrls9bu15LbVuj147FRuYpYU',
    appId: '1:440556450736:web:01fdee71739b61b98bdc75',
    messagingSenderId: '440556450736',
    projectId: 'todo-1ed2c',
    authDomain: 'todo-1ed2c.firebaseapp.com',
    storageBucket: 'todo-1ed2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA10V7rV5lKHWWSX9Kx-450msKtGOwpPMg',
    appId: '1:440556450736:android:cd66079a7a1145e88bdc75',
    messagingSenderId: '440556450736',
    projectId: 'todo-1ed2c',
    storageBucket: 'todo-1ed2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnyHlXQjpgplvNXDDAZ-lV-c9lGqy6qh4',
    appId: '1:440556450736:ios:5725d59503a0f5c38bdc75',
    messagingSenderId: '440556450736',
    projectId: 'todo-1ed2c',
    storageBucket: 'todo-1ed2c.appspot.com',
    iosClientId: '440556450736-16lcu6u2dt0dh6hfkfl4869unenbdft2.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnyHlXQjpgplvNXDDAZ-lV-c9lGqy6qh4',
    appId: '1:440556450736:ios:5725d59503a0f5c38bdc75',
    messagingSenderId: '440556450736',
    projectId: 'todo-1ed2c',
    storageBucket: 'todo-1ed2c.appspot.com',
    iosClientId: '440556450736-16lcu6u2dt0dh6hfkfl4869unenbdft2.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCPcZ_udKbrls9bu15LbVuj147FRuYpYU',
    appId: '1:440556450736:web:cd77b03853e17d498bdc75',
    messagingSenderId: '440556450736',
    projectId: 'todo-1ed2c',
    authDomain: 'todo-1ed2c.firebaseapp.com',
    storageBucket: 'todo-1ed2c.appspot.com',
  );
}
